# Generated by Django 4.2.5 on 2023-09-15 06:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_name',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('class_no', models.IntegerField()),
                ('class_section', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('renamed_filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('post', models.TextField()),
                ('authorize_level', models.IntegerField()),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('classes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('class_no', models.TextField()),
                ('class_sections', models.TextField()),
                ('class_no_days', models.IntegerField()),
                ('class_no_periods', models.IntegerField()),
                ('time_table', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
