# Generated by Django 4.2.6 on 2023-10-29 08:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_days', models.IntegerField()),
                ('no_periods', models.IntegerField()),
                ('name', models.CharField(max_length=5)),
                ('class_teacher', models.IntegerField(unique=True)),
                ('section', models.CharField(max_length=5)),
                ('time_table', models.JSONField(default=[[{}, {}, {}, {}, {}, {}], [{}, {}, {}, {}, {}, {}], [{}, {}, {}, {}, {}, {}], [{}, {}, {}, {}, {}, {}], [{}, {}, {}, {}, {}, {}], [{}, {}, {}, {}, {}, {}], [{}, {}, {}, {}, {}, {}], [{}, {}, {}, {}, {}, {}]])),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('renamed_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('type', models.CharField(default='Teacher', max_length=50)),
                ('post', models.CharField(max_length=10)),
                ('classes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
